# Generated by Django 3.1.4 on 2021-06-06 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='industryChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='positionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('education', models.CharField(choices=[('High School', 'High School'), ('Associate Degree', 'Associate Degree'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree'), ('Doctoral Degree', 'Doctoral Degree')], max_length=100)),
                ('resume', models.FileField(upload_to='')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries+', to='clients.industrychoices')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions+', to='clients.industrychoices')),
            ],
        ),
    ]
