# Generated by Django 3.1.4 on 2021-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210606_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='residency',
            field=models.CharField(choices=[('CAN', 'Canada'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Worker', 'Worker'), ('Visitor', 'Visitor'), ('N/A', 'N/A')], default='N/A', max_length=50),
        ),
    ]
